spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/combus
    username: combus
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

openAPI:
  serviceKey: 5VkF97MjXByHLgBzidNVh5avU8L+X9ZUkzvwT0pE91Y/aaJDiLUIz0peKVyODO6APvL4SWnghH8sBncl0K8q8A==
  tmpKey: fesb%2Bj8fOHKjzliPcpuavNbsf0uBz3UH5e4Fyp3hq35oMWrBXLPEtwlecJr6NZgdNVSzGERT3ORnk3hM6itlVg%3D%3D

